### ISSUE TITLE
The result of odd root is bad for negative numbers

### ISSUE THREAD

**Issue by michal037** [serso/android-calculatorpp#199]
![img_20190101_191205](https://user-images.githubusercontent.com/7441419/50575211-11047280-0dfa-11e9-9c90-8d34c66ad4c8.jpg)

**Comment by GrantMoyer** [comment]
This is correct behavior. 3/2 + 3√(3)/2 is the principal cube root of -9. A number had n distinct nth roots. The principal root is the root with the smallest argument. You can get the root you want by rotating the principal root. Specifically you can define √m(x, m) = √n(x, m) × (-1)^((m - 1) / m)

**Comment by Erhannis** [comment]
Note, btw, that the calculator interprets "-1^2" as "-(1^2)".  With odd roots, it doesn't matter, but fyi.

**Comment by michal037** [comment]
In my opinion, it should be like this:
![equation img](https://user-images.githubusercontent.com/7441419/52309852-ab2f7b80-29a1-11e9-9355-2fc36024d690.gif)

---
It gives this result, but that's not the point:
![eq](https://user-images.githubusercontent.com/7441419/52310931-6ad1fc80-29a5-11e9-8015-35e08c5cc696.png)

In my opinion, the calculator should count according to the rules of mathematics. Or I'm wrong.

---

@GrantMoyer 
> This is correct behavior. 3/2 + 3√(3)/2 is the principal cube root of -9.

Why -9 and not -27? I got lost.

**Comment by GrantMoyer** [comment]
My mistake. 3/2 + i 3√(3)/2 is a cube root of -27, not -9. The fact that the prinicpal root is the one with the smallest argument (counter-clockwise angle from the positive real axis) is by convention, and is not universal.

In all likelihood, √n(x, n) is computed as e^(ln(x) * 1/n). Since complex natural logarithm is a multivalued function, ln(r e^(i θ)) = ln(r) + i (n 2 π + θ) where r is positive and n is an integer, the principal branch of ln(x) (n = 0) is used. This is equivalent to the choice of principal root described above.

**Comment by michal037** [comment]
Don't get me wrong, I didn't really understand where this number came from. I will think how to improve it. btw, thank you for explaining!

**Comment by michal037** [comment]
I think it can be improved in this way. Create a root with cases:
![eqn4](https://user-images.githubusercontent.com/7441419/52526696-b8f44200-2cbc-11e9-9070-8337370e40e0.gif)
